version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: agenda_postgres
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: malobo
      POSTGRES_PASSWORD: 233234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agenda_db
      SPRING_DATASOURCE_USERNAME: malobo
      SPRING_DATASOURCE_PASSWORD: 233234

volumes:
  pgdata:
